spring:
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/communityboard?serverTimezone=Asia/Seoul
    username: root
    password: coldsunn

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 # 최적화 옵션

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace